version: '3.3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './www:/var/www/html'
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  mysqlapp:
    image: mysql:5.6
    container_name: mysqlapp
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
